apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      version: blue
  template:
    metadata:
      labels:
        app: account-service
        version: blue
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: account-service
        image: dhanraj6377/jenkins-ci-project:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker